### ISSUE TITLE
{date} does not get the correct local time

### ISSUE THREAD

**Issue by emisjerry** [jplattel/obsidian-clipper#15] opened 2021-09-06 06:55 UTC
at {date} got 2021-09-06T06:53:14.
But the local time should be 14:53:14 (GMT+8).

**Comment by wjfeeney** [comment] 2021-09-07 05:43
I have the same issue, but I don't think the problem is in this clipper. I'm using MacOS Big Sur, and Apple has a bug in the system time, which for me is 7 hours ahead of my local time, i.e., {date} returned 2021-09-07T05:22:47, but my local time was 2021-09-06T22:22:47. Never had this problem with any prior OS. I know other people have complained of this same problem in Big Sur. I'm going to wait to install Monterey and see if it's fixed; if not, I'll open up a support ticket.

**Comment by tyf2018** [comment] 2021-10-04 06:41
The same issue+1

**Comment by jplattel** [comment] 2021-11-08 17:44
I think the best way is to set a timezone in the configuration, with a best guess on the browser as pre-configured value. I'll look into this :)

**Comment by jplattel** [comment] 2022-02-10 21:26
I'm closing this issue since it was reported I've changed to Moment.js and haven't seen it pop-up. Feel free to open a new issue if it's still there! :)

**Closed by jplattel** 2022-02-10 21:26 UTC
Labels: bug, enhancement
